project:
  type: website

website:
  title: "Jed Toner - Personal Website"
  description: "Data Scientist specializing in Bayesian modeling, forecasting, and machine learning"
  site-url: "https://jedtoner.github.io"
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/jedtoner
      - icon: linkedin
        href: https://www.linkedin.com/in/jed-toner
  
  page-footer:
    right: "Built with Quarto"
    left: "&copy; 2024 Jed Toner"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
