project:
  type: website

website:
  title: "Jed Toner - Portfolio & Blog"
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
  
  page-footer:
    right: "Built with Quarto"
    left: "&copy; 2024 Jed Toner"

format:
  html:
    toc: true
    css: styles.css
    theme: cosmo
